env:
  es2021: true
  node: true
  jest: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  tsconfigRootDir: './server'
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  space-before-function-paren:
    - error
    - named: ignore
